### ISSUE TITLE
Automate bumping Prow itself

### ISSUE THREAD

**Issue by munnerz** [cert-manager/testing#210]
This can be split into a two stage process:

1) Add a postsubmit that runs `bazel run //prow/cluster:production.apply` - this will be the first step, and what ensures the repo is in sync with the actual Prow cluster

2) Add a periodic job that looks up the latest Prow image tag, updates all relevant manifests, and creates a PR to bump image tags across the repo.

Once we have these two, we can configure the periodic to run on some schedule, and this way bumping Prow should be as simple as `/lgtm` and `/approve` 😄

**Comment by inteon** [comment]
We periodically bump the images: https://github.com/cert-manager/testing/blob/18982ca6e0a81fb152d08e29cc1cb22db44ab06d/config/jobs/testing/testing-periodics-trusted.yaml#L98
