### ISSUE TITLE
Add more verify scripts to hack/

### ISSUE THREAD

**Issue by munnerz** [cert-manager/testing#222]
We need verify scripts for:

- [ ] running gazelle
- [ ] running kazel
- [ ] ensuring the repo builds (aka `bazel build //...`)
- [ ] running gofmt
- [x] checking boilerplate headers
- [ ] verifying config (should call checkconfig at a particular path, or run the docker image)

**Comment by inteon** [comment]
We don't use bazel anymore. The desired verify commands seem to be part of this repo now.
