### ISSUE TITLE
Migrate cert-manager testgrid integration from Transfigure to Config Merger

### ISSUE THREAD

**Issue by wallrj** [cert-manager/testing#629]
Transfigure is deprecated in favor of [Config Merger](https://github.com/kubernetes/test-infra/blob/master/testgrid/merging.md). See [Migration](https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/transfigure#migration) for details.

And Transfigure sometimes fails with false errors caused by problems in kubernetes/test-infra, preventing us merging unrelated changes to this repo, 
 * https://github.com/jetstack/testing/pull/628#issuecomment-1033756702

Istio have already completed the migration. Here's their issue: 
 * https://github.com/istio/test-infra/issues/3533

[TODO](https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/transfigure#migration)
- [x] Add  Configurator jobs (like [this example](https://github.com/kubernetes/test-infra/blob/master/testgrid/config-merger-prowjob-example.yaml)) to Prow instance.
   - [x] #673
   - [x] #676
- [x] In the same PR, in this repository, add your instance to the [mergelists](https://github.com/kubernetes/test-infra/blob/master/config/mergelists) and delete the gen-config.yaml file that Transfigure has been maintaining.
   - [x] https://github.com/kubernetes/test-infra/pull/26209
- [x] Delete any leftover Transfigure jobs and close any leftover Transfigure PRs.

**Comment by inteon** [comment]
I think this has been completed, also the jetstack tests have been removed from https://testgrid.k8s.io/ (see https://github.com/kubernetes/test-infra/pull/29269).
