### ISSUE TITLE
Move infra image building off Docker

### ISSUE THREAD

**Issue by irbekrm** [cert-manager/testing#642]
Currently all images in [./images](https://github.com/jetstack/testing/tree/master/images) are built using Docker.
Some of the downsides:
- slow builds
- requires to run image build pods as privileged
- [somewhat complex Docker setup](https://github.com/jetstack/testing/blob/master/images/bazelbuild/runner) (but this is needed for e2e tests which setup kind cluster too)
- building images on Kubernetes with Docker is generally not recommended (@BeckyPauley pointed me at [this doc](https://cloud.google.com/kubernetes-engine/docs/concepts/using-containerd#building_container_images_with_containerd))

We could instead use a more lightweight build mechanism such as [ko](https://github.com/google/ko) which is already used for a number of internal projects at Jetstack or a 'kube native' image build mechanism like [kaniko](https://github.com/GoogleContainerTools/kaniko)

Note: we should aim to use similar tooling across cert-manager projects

**Comment by irbekrm** [comment]
Or maybe nix? https://github.com/jetstack/testing/commit/0ebd3d851d929769e120c805c9a8e1f247ec9394

**Comment by inteon** [comment]
I don't think we still plan to move away from docker build for this project.
The images are not build that frequently, and we only require amd64 images.

NOTE: Most of our other projects no longer use docker, we use ko instead. ko is much faster for multi-architecture builds.
